version: "3.4"
services:
  db:
    container_name: sandbox_db
    image: mysql:5.7
    tty: true
    command:
      - --general-log=true
      - --general-log-file=/var/tmp/general.log
    ports:
      - "3306:3306"
    volumes:
      - ./database/sqls:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"