output   = "my_models"
wipe     = true
no-tests = true

[mysql]
dbname  = "sandbox_db"
host    = "localhost"
port    = 3306
user    = "root"
pass    = "password"
sslmode = "false"

[aliases.tables.issues.columns]
bad_col_name     = "GoodColName"

